Read Me

Current issue with code:

Rolling the dices...
The values are....
3
1
Traceback (most recent call last):
  File ".\dice.py", line 13, in <module>
    roll_again = raw_input("Roll the dices a
NameError: name 'raw_input' is not defined
